### ISSUE TITLE
Systems suggestions

### ISSUE THREAD

**Issue by brimwats** [spatialresearch/productivitypatterns#4]
Just noticed that you had colon classification! You probably also want:

- Universial Decimal System 
- Bliss Classidification
- Cutter Classification (Cutter 1-6 get increasingly complex)
- Library of Congress Classification and Library of Congress Subject Headings (LCSH)

**Comment by spatialresearch** [comment]
I haven't looked into library classification systems yet. where to draw the line for personal information + knowledge management system is the working problem. does it need library classification systems at scale?

**Comment by brimwats** [comment]
I suspect the answer to that is yes—or at least, I hope so as that's my PhD research! I've done a few different discussions on this for the obisidian community, but it is absolutely sensible to exclude!

**Comment by spatialresearch** [comment]
right now everything is classified under knowledge in all the tools communities. which, I think is a problem of sorts. ideally, a `modern second brain` has documents, information, and knowledge, these as distinct states not accounted for. library classification systems will become necessary when PDMs are considered as a separate and isolated sector to engage with in addition to PIM and PKM systems. but it is very dependant on a knowledge production workflow. thanks for the nudge will address it in time I guess.
